### PR TITLE
Add 'required' validator with allowEmptyString? argument

### PR DESCRIPTION
**Pull request by jschill**

### CODE REVIEW

**Comment by parris** [comment]
Hmmm, thanks for adding required to the validators. Does it make sense to augment the `string` validator instead of adding a new option to required?

**Comment by jschill** [comment]
I'm not sure I follow. How would that api look like?

**Comment by parris** [comment]
I was imaging that you don't even need `.required()` `iz.string('')` should be true as should `iz.string(' ')` while `iz.string(undefined)` is false. 

We're already simply doing a type check for strings with iz.string https://github.com/parris/iz/blob/master/src/basicValidators/string.js

Therefore; you don't even need required for this use case.

**Comment by parris** [comment]
https://github.com/parris/iz/blob/master/spec/validators.spec.js#L19-L37

**Pull request closed without merging**
